### ISSUE TITLE
Instructions missing the old text on include if 80% or more funded (etc.)

### ISSUE THREAD

**Issue by mqli322** [NYCPlanning/labs-ceqr#184]
![image](https://user-images.githubusercontent.com/30453673/47592835-fec21000-d942-11e8-9688-f45f81bf8104.png)

**Comment by pichot** [comment]
I removed this in favor of the tooltips that said the same thing. Do you think we should repeat here?

**Comment by mqli322** [comment]
Should be repeated there so the user has predictability – knowing that the instructions box is the first thing to look at to understand the intent of that section
