### ISSUE TITLE
Schools - lock March 2014 multipliers to Nov 2017 data

### ISSUE THREAD

**Issue by mqli322** [NYCPlanning/labs-ceqr#199]
Just realized we can't interchange between multipliers and new data bc the students introduced by new housing is tied to the multipliers

**Comment by pichot** [comment]
So the only valid states are:

| Data | Multipliers |
| --- | --- |
| Nov 17 | March 14 |
| Nov 17 | Nov 18 |
| Nov 18 | Nov 18 |

**Comment by mqli322** [comment]
Just the yellow highlighted are valid. And ofcourse future:

Nov 19 data, Nov 18 multipliers
Nov 20 data, Nov 18 multipliers
